# Generated by Django 2.2.2 on 2019-07-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.CharField(max_length=50)),
                ('ename', models.CharField(max_length=50)),
                ('esalary', models.FloatField()),
                ('emobile', models.IntegerField()),
            ],
        ),
    ]
